version: "3.8"

services:
  namenode:
    build:
      context: hadoop/.
      target: build_hadoop
    hostname: namenode

# Сначала запусти меня
#    command: ["hdfs", "namenode", "-format", "-force"]
# А уже потом спокойно запускай меня
    command: ["hdfs", "namenode"]
    env_file:
      - ./hadoop.env
    ports:
      - 9870:9870
    volumes:
      - hadoop_namenode:/tmp/hadoop-root/
      - ./hadoop_conf/etc:/opt/hadoop/etc

  datanode1:
    build:
      context: hadoop/.
      target: build_hadoop
    hostname: datanode
    command: ["hdfs", "datanode"]
    env_file:
      - ./hadoop.env
    ports:
      - 9864:9864
    volumes:
      - hdfs1:/tmp/hadoop-hadoop
      - ./hadoop_conf/etc:/opt/hadoop/etc

  resourcemanager:
    build:
      context: hadoop/.
      target: build_hadoop
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088
    volumes:
      - resourcemanager:/tmp/hadoop-hadoop
      - ./hadoop_conf/etc:/opt/hadoop/etc

  nodemanager1:
    build:
      context: hadoop/.
      target: build_hadoop
    hostname: nodemanager1
    command: ["yarn", "nodemanager"]
    ports:
      - 19888:19888
      - 8042:8042
    expose:
      - 19888
      - 8042
    volumes:
      - nodemanager1:/tmp/hadoop-hadoop
      - ./hadoop_conf/etc:/opt/hadoop/etc

  postgres:
    image: postgres:10
    hostname: postgres
    environment:
      POSTGRES_DB: 'metastore_db'
      POSTGRES_USER: 'hive'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - hive-db:/var/lib/postgresql

  metastore:
    build:
      context: hadoop/.
      target: hive_hadoop
    hostname: metastore
    # Сначала запусти меня
    #    command: ["schematool", "--dbType", "postgres", "--initSchema"]
    # А уже потом спокойно запускай меня
    command: [ "hive", "--service", "metastore" ]
    environment:
      - HIVE_SERVER2_THRIFT_PORT=10000
    ports:
      - 9083:9083
    expose:
      - 9083
    volumes:
      - ./hadoop_conf/etc:/opt/hadoop/etc
      - ./hive_conf:/opt/hive/conf

  hiveserver2:
    build:
      context: hadoop/.
      target: hive_hadoop
    environment:
      - HIVE_SERVER2_THRIFT_PORT=10000
    command: [ "hive", "--service", "hiveserver2" , "--hiveconf", "hive.root.logger=INFO,console"]
    ports:
      - 10000:10000
      - 10002:10002
    expose:
      - 10000
      - 10002
    volumes:
      - ./hadoop_conf/etc:/opt/hadoop/etc
      - ./hive_conf:/opt/hive/conf

  jupyter:
    build:
      context: hadoop/.
      target: jupyter_hadoop
    env_file:
      - ./hadoop.env
    ports:
      - 8888:8888
    volumes:
      - ./hadoop_conf/etc:/opt/hadoop/etc
      - ./notebooks:/opt/notebooks
    command: ["jupyter", "notebook", "--allow-root", "--ip", "0.0.0.0"]

#  Вот этого монстра запускай на свой страх и риск
#  zeppelin:
#    build:
#      context: hadoop/.
#      target: zeppelin_hadoop
#    env_file:
#      - ./hadoop.env
#    ports:
#      - 8080:8080
#    volumes:
#      - ./hadoop_conf/etc:/opt/hadoop/etc
#      - ./hive_conf:/opt/hive/conf
#    command: ["bash", "/opt/zeppelin/bin/zeppelin.sh"]

networks:
  default:
    name: yohoho

volumes:
  hive-db:
  hdfs1:
  resourcemanager:
  nodemanager1:
  hadoop_namenode:

