version: "3.8"

services:
  namenode:
    build:
      context: hadoop/.
      target: build_hadoop
    hostname: namenode
#     Сначала запусти меня
    command: ["hdfs", "namenode", "-format", "-force"]
#     А уже потом спокойно запускай меня
#    command: ["hdfs", "namenode"]
    env_file:
      - ./hadoop.env
    ports:
      - 9870:9870
    volumes:
      - hadoop_namenode:/tmp/hadoop-root/
      - ./hadoop_conf/etc:/opt/hadoop/etc

  datanode1:
    build:
      context: hadoop/.
      target: build_hadoop
    hostname: datanode
    command: ["hdfs", "datanode"]
    env_file:
      - ./hadoop.env
    ports:
      - 9864:9864
    volumes:
      - hdfs1:/tmp/hadoop-hadoop
      - ./hadoop_conf/etc:/opt/hadoop/etc

  resourcemanager:
    build:
      context: hadoop/.
      target: build_hadoop
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    env_file:
      - ./hadoop.env
    ports:
      - 8088:8088
    volumes:
      - resourcemanager:/tmp/hadoop-hadoop
      - ./hadoop_conf/etc:/opt/hadoop/etc

  nodemanager1:
    build:
      context: hadoop/.
      target: build_hadoop
    hostname: nodemanager1
    command: ["yarn", "nodemanager"]
    env_file:
      - ./hadoop.env
    ports:
      - 19888:19888
      - 8042:8042
    expose:
      - 19888
      - 8042
    volumes:
      - nodemanager1:/tmp/hadoop-hadoop
      - ./hadoop_conf/etc:/opt/hadoop/etc

  jupyter:
    build:
      context: hadoop/.
      target: jupyter_hadoop
    env_file:
      - ./hadoop.env
    ports:
      - 8888:8888
    volumes:
      - ./hadoop_conf/etc:/opt/hadoop/etc
      - ./notebooks:/opt/notebooks
    command: ["jupyter", "notebook", "--allow-root", "--ip", "0.0.0.0"]

networks:
  default:
    name: yohoho

volumes:
  hdfs1:
  resourcemanager:
  nodemanager1:
  hadoop_namenode:

